# 璇峰弬闃?https://aka.ms/customizecontainer 浠ヤ簡瑙ｅ浣曡嚜瀹氫箟璋冭瘯瀹瑰櫒锛屼互鍙?Visual Studio 濡備綍浣跨敤姝?Dockerfile 鐢熸垚鏄犲儚浠ユ洿蹇湴杩涜璋冭瘯銆?

# 姝ら樁娈电敤浜庡湪蹇€熸ā寮?榛樿涓鸿皟璇曢厤缃?涓嬩粠 VS 杩愯鏃?
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
EXPOSE 8080
COPY . .
ENTRYPOINT ["dotnet", "TcmAiDiagnosis.Web.dll"]